from __future__ import annotations

import hashlib

from riichi_analysis_engine.analysis_observation import (
    PLANE_CHANNEL_NAMES,
    IncrementalTilePlaneEncoder,
)
from riichi_analysis_engine.analysis_state import PublicHistoryState


def _events() -> list[dict[str, object]]:
    hands = [
        ["5m", "5mr", "6m", "7m", "1p", "2p", "3p", "1s", "2s", "3s", "E", "E", "E"],
        ["1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m", "1p", "2p", "3p", "4p"],
        ["2m", "2m", "2m", "2m", "5m", "6m", "7m", "8m", "9m", "1s", "2s", "3s", "4s"],
        ["3m", "3m", "3m", "3m", "5p", "6p", "7p", "8p", "9p", "E", "S", "W", "N"],
    ]
    return [
        {"type": "start_kyoku", "bakaze": "E", "kyoku": 1, "honba": 1, "kyotaku": 0, "oya": 0, "scores": [30000, 25000, 24000, 21000], "dora_marker": "1m", "tehais": hands},
        {"type": "tsumo", "actor": 2, "pai": "6s"},
        {"type": "dahai", "actor": 2, "pai": "6s", "tsumogiri": True},
        {"type": "reach", "actor": 2},
        {"type": "reach_accepted", "actor": 2, "scores": [30000, 25000, 23000, 21000]},
        {"type": "dora", "dora_marker": "4p"},
        {"type": "chi", "actor": 1, "target": 0, "pai": "3m", "consumed": ["1m", "2m"]},
        {"type": "pon", "actor": 2, "target": 1, "pai": "2m", "consumed": ["2m", "2m"]},
        {"type": "ankan", "actor": 0, "consumed": ["E", "E", "E", "E"]},
        {"type": "kakan", "actor": 2, "pai": "2m", "consumed": ["2m", "2m", "2m"]},
        {"type": "daiminkan", "actor": 3, "target": 2, "pai": "3m", "consumed": ["3m", "3m", "3m"]},
    ]


def test_public_history_schema_matches_the_proven_v23_encoder() -> None:
    names = hashlib.sha256("\n".join(PLANE_CHANNEL_NAMES).encode()).hexdigest()
    assert names == "2e4b8123d406d47f4204f74f9d31846ef191b396d74618d4145022bf778e4106"

    state = PublicHistoryState()
    encoder = IncrementalTilePlaneEncoder()
    digest = hashlib.sha256()
    for event in _events():
        state.process(event)
        encoder.advance(event, state)
        for perspective in range(4):
            digest.update(encoder.encode(event, perspective).astype("<f4").tobytes())

    # Generated by the established mj_shanten_predictor_v2_3 encoder. The
    # sequence covers every supported public frame event and all four views.
    assert digest.hexdigest() == "e2b2bbb40579e908df23ab6a50f1cfeab314514cf762f244d3c66fb5ed519607"
